### ISSUE TITLE
required package @essential-projects/core_contracts is not defined as dependency in package.json

### ISSUE THREAD

**Issue by stheuer** [essential-projects/services#6]
#### Describe your issue

required package @essential-projects/core_contracts is not defined as dependency in package.json

#### How can others reproduce the issue?
- File ioc.schema.js requires @essential-projects/core_contracts.
- package.json does not have a dependency on @essential-projects/core_contracts
#### Possible solution

add dependency @essential-projects/core_contracts to package.json

#### What's your setup

- OS (`Windows/OS X/Linux` + `version`):

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [ x] I've checked if this issue already exists
- [x ] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by ppoetschke** [comment]
This is already addressed with https://github.com/essential-projects/services/pull/5
